[package]
name = "sdb-shim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.155"
libloading = "0.8.5"
fast_log = "1.7.3"
log = "0.4.22"
flate2 = "1.0.33"
